-- Add migration script here
CREATE TABLE IF NOT EXISTS vuln_information (
    id BIGSERIAL PRIMARY KEY,
    key TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    severity TEXT NOT NULL DEFAULT '',
    cve TEXT NOT NULL DEFAULT '',
    disclosure TEXT NOT NULL DEFAULT '',
    solutions TEXT NOT NULL DEFAULT '',
    reference_links TEXT [] NOT NULL DEFAULT '{}',
    tags TEXT [] NOT NULL DEFAULT '{}',
    github_search TEXT [] NOT NULL DEFAULT '{}',
    reasons TEXT [] NOT NULL DEFAULT '{}',
    source TEXT NOT NULL DEFAULT '',
    source_name TEXT NOT NULL DEFAULT '',
    pushed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sync_task (
    id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL DEFAULT '',
    interval_minutes INTEGER NOT NULL DEFAULT 15,
    status BOOLEAN NOT NULL DEFAULT FALSE,
    job_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sync_task_record (
    id BIGSERIAL PRIMARY KEY,
    task_id TEXT NOT NULL DEFAULT '',
    started_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    success BOOLEAN NOT NULL DEFAULT FALSE,
    error_message TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin_user (
    id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ding_bot_config (
    id BIGSERIAL PRIMARY KEY,
    access_token TEXT NOT NULL,
    secret_token TEXT NOT NULL,
    status BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
)